### ISSUE TITLE
Publish new version of the gem?

### ISSUE THREAD

**Issue by seanthingee** [capistrano-s3/capistrano-s3#63]
ruby: 3.3.0
capistrano-s3: 2.4.0

Getting an error while trying to deploy: 
```
cap aborted!
NoMethodError: undefined method `exists?' for class File (NoMethodError)

          if File.exists? LAST_PUBLISHED_FILE
                 ^^^^^^^^
Did you mean?  exist?
```

Tracked it down to: `lib/capistrano/s3/publisher.rb:116`. Appears to be fixed in 492100565301b8ea5e3734f5739095ea895f6bf0 from Jan 2019 but is not included in 2.4.0.

Since that was 5 years ago, would it be possible to release a new version?

**Comment by exoszajzbuk** [comment]
@aleksandrs-ledovskis would it be possible to release the changes in `master` as a new gem version?

**Comment by exoszajzbuk** [comment]
thank you for the quick pre-release! although the following problem is present with

`capistrano 3.19.2`
`capistrano-s3 3.0.0.pre`
`ruby3.2.0`

```
cap aborted!
NoMethodError: undefined method `new' for false:FalseClass (NoMethodError)
        @engine.new(stack).parse(xml.to_s)
               ^^^^
Did you mean?  now
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/xml/parser.rb:44:in `parse'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/response/body.rb:37:in `parse'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/response/body.rb:21:in `apply'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/response/parser.rb:32:in `extract_body'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/response/parser.rb:13:in `apply'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/handler.rb:8:in `block in call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/response.rb:45:in `block in on'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/http/response.rb:139:in `block in on_success'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/http/response.rb:166:in `block in listener'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/http/response.rb:130:in `on_done'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/http/response.rb:137:in `on_success'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/response.rb:44:in `on'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/rest/handler.rb:8:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/endpoint_pattern.rb:27:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/endpoint_discovery.rb:67:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/logging.rb:39:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/request.rb:70:in `send_request'
/var/lib/gems/3.2.0/gems/aws-sdk-core-2.11.632/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/var/lib/gems/3.2.0/gems/capistrano-s3-3.0.0.pre/lib/capistrano/s3/publisher.rb:36:in `publish!'
/var/lib/gems/3.2.0/gems/capistrano-s3-3.0.0.pre/lib/capistrano/tasks/capistrano_3.rb:34:in `block (3 levels) in <top (required)>'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:281:in `block in execute'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:281:in `each'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:281:in `execute'
/var/lib/gems/3.2.0/gems/airbrussh-1.5.3/lib/airbrussh/rake/context.rb:58:in `execute'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:199:in `synchronize'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:188:in `invoke'
/var/lib/gems/3.2.0/gems/capistrano-3.19.2/lib/capistrano/dsl.rb:26:in `invoke'
/var/lib/gems/3.2.0/gems/capistrano-s3-3.0.0.pre/lib/capistrano/tasks/capistrano_3.rb:44:in `block (2 levels) in <top (required)>'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:281:in `block in execute'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:281:in `each'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:281:in `execute'
/var/lib/gems/3.2.0/gems/airbrussh-1.5.3/lib/airbrussh/rake/context.rb:58:in `execute'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:199:in `synchronize'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:241:in `each'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:241:in `invoke_prerequisites'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:199:in `synchronize'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:188:in `invoke'
/var/lib/gems/3.2.0/gems/capistrano-3.19.2/lib/capistrano/dsl.rb:26:in `invoke'
/var/lib/gems/3.2.0/gems/capistrano-3.19.2/lib/capistrano/tasks/framework.rake:64:in `block (2 levels) in <top (required)>'
/var/lib/gems/3.2.0/gems/capistrano-3.19.2/lib/capistrano/tasks/framework.rake:63:in `each'
/var/lib/gems/3.2.0/gems/capistrano-3.19.2/lib/capistrano/tasks/framework.rake:63:in `block in <top (required)>'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:281:in `block in execute'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:281:in `each'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:281:in `execute'
/var/lib/gems/3.2.0/gems/airbrussh-1.5.3/lib/airbrussh/rake/context.rb:58:in `execute'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:199:in `synchronize'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/task.rb:188:in `invoke'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/application.rb:188:in `invoke_task'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/application.rb:138:in `each'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/application.rb:138:in `block in top_level'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/application.rb:147:in `run_with_threads'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/application.rb:132:in `top_level'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/application.rb:83:in `block in run'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/application.rb:214:in `standard_exception_handling'
/var/lib/gems/3.2.0/gems/rake-13.3.0/lib/rake/application.rb:80:in `run'
/var/lib/gems/3.2.0/gems/capistrano-3.19.2/lib/capistrano/application.rb:14:in `run'
/var/lib/gems/3.2.0/gems/capistrano-3.19.2/bin/cap:3:in `<top (required)>'
/usr/local/bin/cap:25:in `load'
/usr/local/bin/cap:25:in `<main>'
Tasks: TOP => deploy:s3:upload_files
The deploy has failed with an error: undefined method `new' for false:FalseClass
** Invoke deploy:failed (first_time)
** Execute deploy:failed
** DEPLOY FAILED
```

**Comment by exoszajzbuk** [comment]
thank you, it is working now with ruby3
